version: "3.8"
services:
  database:
    container_name: MSSQL-container
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "xYm9Cek412ZY"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"

  maildev:
    container_name: maildev-container
    image: maildev/maildev:latest
    restart: always
    environment:
      TZ: "${TIMEZONE}"
      MAILDEV_WEB_PORT: "${MAILDEV_WEB_PORT}"
      MAILDEV_SMTP_PORT: "${MAILDEV_SMTP_PORT}"
    ports:
      - "${MAILDEV_WEB_PORT}:${MAILDEV_WEB_PORT}"
      - "${MAILDEV_SMTP_PORT}:${MAILDEV_SMTP_PORT}"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - maildev
    ports:
      - "3000:3000"