version: "3.8"
services:

  database:
    container_name: MSSQL-container
    hostname: mssql-erp
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DB_USER_PASSWORD}"
      MSSQL_PID: "Express"
    ports:
      - "${DB_PORT}:${DB_PORT}"

  maildev:
    container_name: maildev-container
    image: maildev/maildev:latest
    restart: always
    environment:
      TZ: "${TIMEZONE}"
      MAILDEV_WEB_PORT: "${MAILDEV_WEB_PORT}"
      MAILDEV_SMTP_PORT: "${MAILDEV_SMTP_PORT}"
    ports:
      - "${MAILDEV_WEB_PORT}:${MAILDEV_WEB_PORT}"
      - "${MAILDEV_SMTP_PORT}:${MAILDEV_SMTP_PORT}"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
